-- 보호소에서 중성화한 동물
SELECT ANIMAL_INS.ANIMAL_ID,ANIMAL_INS.ANIMAL_TYPE,ANIMAL_INS.NAME
FROM ANIMAL_INS, ANIMAL_OUTS
WHERE ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
AND ANIMAL_INS.SEX_UPON_INTAKE != ANIMAL_OUTS.SEX_UPON_OUTCOME
ORDER BY ANIMAL_ID