SELECT A.CAR_ID, A.CAR_TYPE, ROUND(30 * A.DAILY_FEE * ((100 - C.DISCOUNT_RATE) / 100)) as FEE
FROM CAR_RENTAL_COMPANY_CAR as A
         JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as B
              ON A.CAR_ID = B.CAR_ID
         JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as C
              ON A.CAR_TYPE=C.CAR_TYPE AND A.CAR_TYPE in ("SUV", "세단") AND C.DURATION_TYPE="30일 이상"
WHERE A.CAR_ID NOT IN (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (START_DATE BETWEEN "2022-11-01" AND "2022-11-30") OR (END_DATE BETWEEN "2022-11-01" AND "2022-11-30") OR (DATE_FORMAT(START_DATE, "%Y-%m-%d") < "2022-11-01" AND DATE_FORMAT(END_DATE, "%Y-%m-%d") > "2022-11-30")
) AND A.CAR_ID NOT IN (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR A
             JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as B
                  ON A.CAR_TYPE=B.CAR_TYPE AND A.CAR_TYPE in ("세단", "SUV")
    WHERE ROUND(30 * A.DAILY_FEE * ((100 - B.DISCOUNT_RATE) / 100)) < 500000 OR ROUND(30 * A.DAILY_FEE * ((100 - B.DISCOUNT_RATE) / 100)) >= 2000000
)
GROUP BY A.CAR_ID
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC;

