/* 풀이 1 */
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, '%Y-%m-%d') as 날짜
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

/* 풀이2
    SELECT ANIMAL_ID, NAME, LEFT(DATE(DATETIME), 10) as 날짜
    FROM ANIMAL_INS
    ORDER BY ANIMAL_ID
*/