SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE A
JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_NAME IN (
    SELECT *
    FROM (
        SELECT A.MEMBER_NAME
        FROM MEMBER_PROFILE A
        JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
        GROUP BY A.MEMBER_ID
        ORDER BY COUNT(A.MEMBER_NAME) DESC
        LIMIT 1) as t
)
ORDER BY REVIEW_DATE, REVIEW_TEXT