SELECT CAR_ID, ROUND(SUM(DATEDIFF(END_DATE, START_DATE)+1)/COUNT(CAR_ID), 1) as AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC