SELECT F.CATEGORY, F.PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F,
(SELECT CATEGORY, MAX(PRICE) AS MPRICE
 FROM FOOD_PRODUCT
 GROUP BY CATEGORY
) AS M
WHERE F.CATEGORY = M.CATEGORY AND F.PRICE = M.MPRICE
AND F.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY F.PRICE DESC