SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE P ON R.MEMBER_ID = P.MEMBER_ID
JOIN (
    SELECT MEMBER_ID, COUNT(*) AS REVIEWS
    FROM REST_REVIEW
    GROUP BY 1
    ORDER BY 2 DESC
    LIMIT 1
) C ON R.MEMBER_ID = C.MEMBER_ID
ORDER BY 3, 2