SELECT CATEGORY, PRICE as MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE PRICE IN (
        SELECT MAX(PRICE)
        FROM FOOD_PRODUCT
        GROUP BY CATEGORY
)
GROUP BY CATEGORY
HAVING CATEGORY REGEXP '과자|국|김치|식용유'
ORDER BY MAX_PRICE DESC