/* 풀이1 */
WITH RECURSIVE NEW AS (
    SELECT 0 as HOUR, 0 as COUNT
    UNION ALL
    SELECT HOUR + 1, 0 as COUNT FROM NEW
    WHERE HOUR < 23
), NEW2 AS (
    SELECT HOUR(DATETIME) as HOUR, COUNT(ANIMAL_ID) as COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
    ORDER BY HOUR
)

SELECT A.HOUR, IF(B.COUNT IS NULL, 0, B.COUNT) as COUNT
FROM NEW A
LEFT JOIN NEW2 B ON A.HOUR = B.HOUR

/* 풀이2 
    WITH RECURSIVE NEW AS (
    SELECT 0 as HOUR
    UNION ALL
    SELECT HOUR + 1 FROM NEW
    WHERE HOUR < 23
    )

    SELECT A.HOUR as HOUR, COUNT(B.HOUR) as COUNT
    FROM NEW A
    LEFT JOIN (
        SELECT ANIMAL_ID, EXTRACT(HOUR FROM DATETIME) as HOUR FROM ANIMAL_OUTS
    ) B ON A.HOUR = B.HOUR
    GROUP BY A.HOUR
    ORDER BY HOUR
*/