WITH NEW as (
SELECT CAR_ID, IF(DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-10-16' AND DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-10-16', '대여중', '대여 가능') as AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID, AVAILABILITY
ORDER BY CAR_ID DESC
)

SELECT CAR_ID, IF(COUNT(AVAILABILITY)>1, '대여중', '대여 가능') as AVAILABILITY
FROM NEW
GROUP BY CAR_ID