/* 풀이1 */
WITH NEW AS (
    SELECT *
    FROM REST_INFO
    WHERE FAVORITES IN (
        SELECT MAX(FAVORITES)
        FROM REST_INFO
        GROUP BY FOOD_TYPE
    )
    GROUP BY FOOD_TYPE
)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM NEW
ORDER BY FOOD_TYPE DESC

/* 풀이2
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
    FROM REST_INFO
    WHERE FAVORITES IN (
            SELECT MAX(FAVORITES)
            FROM REST_INFO
            GROUP BY FOOD_TYPE
    )
    GROUP BY FOOD_TYPE
    ORDER BY FOOD_TYPE DESC
*/