SELECT YEAR(B.SALES_DATE) as YEAR, MONTH(B.SALES_DATE) as MONTH, A.GENDER as GENDER, count(DISTINCT(A.USER_ID)) as USERS
FROM USER_INFO as A
    JOIN ONLINE_SALE as B
ON A.USER_ID = B.USER_ID
WHERE A.GENDER is not NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER