SELECT B.INGREDIENT_TYPE, sum(A.TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF as A
         JOIN ICECREAM_INFO as B
              ON A.FLAVOR = B.FLAVOR
GROUP BY B.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;