WITH RECURSIVE HOURS AS
                   (
                       SELECT 0 as HOUR
UNION ALL
SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
    )

SELECT A.HOUR as HOUR, count(B.ANIMAL_ID) as COUNT
FROM HOURS as A
    LEFT JOIN ANIMAL_OUTS as B
ON A.HOUR = HOUR(B.DATETIME)
GROUP BY A.HOUR
