SELECT YEAR(B.SALES_DATE) as YEAR, MONTH(B.SALES_DATE) as MONTH, COUNT(DISTINCT(B.USER_ID)) as PUCHASED_USERS, ROUND(COUNT(DISTINCT(B.USER_ID)) / (
    SELECT COUNT(*)
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
    ), 1) as PUCHASED_RATIO
FROM USER_INFO as A
    JOIN ONLINE_SALE as B
ON A.USER_ID = B.USER_ID
WHERE YEAR(A.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;
