SELECT ai.ANIMAL_ID, ai.ANIMAL_TYPE, ai.NAME
FROM ANIMAL_INS as ai
         JOIN ANIMAL_OUTS as ao
              ON ai.ANIMAL_ID=ao.ANIMAL_ID
WHERE (ai.SEX_UPON_INTAKE NOT LIKE "%Spayed%" AND ai.SEX_UPON_INTAKE NOT LIKE "%Neutered%") AND (ao.SEX_UPON_OUTCOME LIKE "%Spayed%" or ao.SEX_UPON_OUTCOME LIKE "%Neutered %")
ORDER BY ai.ANIMAL_ID;
