/* 풀이1 */
SELECT B.HISTORY_ID, ROUND((DATEDIFF(B.END_DATE, B.START_DATE)+1) * A.DAILY_FEE * (
    CASE
        WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 < 7 THEN 1
        WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 < 30 THEN 0.95
        WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 < 90 THEN 0.92
        ELSE 0.85
    END
)) as FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC

/* 풀이2
    WITH NEW_TABLE AS
    (
        SELECT A.HISTORY_ID, A.CAR_ID, B.DAILY_FEE, (DATEDIFF(A.END_DATE, A.START_DATE)+1) as DATEDIFF
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
        JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
        WHERE B.CAR_TYPE = '트럭'
    )

    SELECT HISTORY_ID, ROUND(
            CASE
                WHEN DATEDIFF < 7 THEN DAILY_FEE*DATEDIFF
                WHEN DATEDIFF < 30 THEN (DAILY_FEE-(DAILY_FEE*0.05))*DATEDIFF
                WHEN DATEDIFF < 90 THEN (DAILY_FEE-(DAILY_FEE*0.08))*DATEDIFF
                ELSE (DAILY_FEE-(DAILY_FEE*0.15))*DATEDIFF
            END
    ) as FEE
    FROM NEW_TABLE
    ORDER BY FEE DESC, HISTORY_ID DESC
*/