-- 대여기록이 존재하는 자동차 리스트 구하기
SELECT DISTINCT(CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY , CAR_RENTAL_COMPANY_CAR
WHERE 
CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID = CAR_RENTAL_COMPANY_CAR.CAR_ID
AND 
CAR_TYPE = '세단'
AND
MONTH(START_DATE) = 10
ORDER BY CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID DESC