SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES*B.PRICE) as 'TOTAL_SALES'
from BOOK_SALES BS join BOOK B using(BOOK_ID) join AUTHOR A using(AUTHOR_ID)
where left(BS.SALES_DATE,7)='2022-01'
group by A.AUTHOR_ID,B.CATEGORY
order by A.AUTHOR_ID asc, B.CATEGORY desc;