-- 저자 별 카테고리 별 매출액 집계하기
SELECT AUTHOR.AUTHOR_ID,AUTHOR.AUTHOR_NAME, BOOK.CATEGORY,SUM(BOOK.PRICE*BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK, AUTHOR , BOOK_SALES
WHERE BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID AND
BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
AND YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE)=1
GROUP BY AUTHOR.AUTHOR_ID ,AUTHOR.AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR.AUTHOR_ID , CATEGORY DESC