SELECT ai.AUTHOR_ID as AUTHOR_ID, ai.AUTHOR_NAME as AUTHOR_NAME, bi.CATEGORY as CATEGORY, sum(bi.PRICE * bs.SALES) as TOTAL_SALES
FROM BOOK as bi
         JOIN AUTHOR as ai
              ON bi.AUTHOR_ID=ai.AUTHOR_ID
         JOIN BOOK_SALES as bs
              on bi.BOOK_ID=bs.BOOK_ID
WHERE DATE_FORMAT(bs.SALES_DATE, "%Y-%m")="2022-01"
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;