SELECT C.APNT_NO,A.PT_NAME, C.PT_NO,C.MCDP_CD,B.DR_NAME,C.APNT_YMD
FROM APPOINTMENT as C
         JOIN PATIENT A
              ON A.PT_NO = C.PT_NO
         JOIN DOCTOR B
              ON B.DR_ID = C.MDDR_ID
WHERE C.MCDP_CD = 'CS' AND DATE_FORMAT(C.APNT_YMD, "%Y-%m-%d")="2022-04-13" AND C.APNT_CNCL_YN = 'N'
GROUP BY PT_NAME
ORDER BY C.APNT_YMD;