/*
 서브쿼리 
 WHERE PRICE = (SELECT MAX(PRICE) PRICE FROM FOOD_PRODUCT)
*/


SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) PRICE FROM FOOD_PRODUCT)