/*
테이블 합칠땐 UNION 사용하기

*/


(
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE MONTH(SALES_DATE) = 03 AND YEAR(SALES_DATE) = 2022
)
UNION
(
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE MONTH(SALES_DATE) = 03 AND YEAR(SALES_DATE) = 2022
)
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID