WITH vipdata AS (
    SELECT MEMBER_ID, COUNT(DISTINCT REVIEW_ID) AS RCNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY RCNT DESC
    LIMIT 1
)

SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE m
INNER JOIN vipdata v
    ON m.MEMBER_ID = v.MEMBER_ID
INNER JOIN REST_REVIEW r
    ON m.MEMBER_ID = r.MEMBER_ID
ORDER BY REVIEW_DATE,REVIEW_TEXT