SELECT ri.REST_ID, ri.REST_NAME, ri.FOOD_TYPE, ri.FAVORITES, ri.ADDRESS, ROUND(avg(rv.REVIEW_SCORE), 2) as SCORE
FROM REST_REVIEW as rv
         JOIN REST_INFO as ri
              ON rv.REST_ID=ri.REST_ID
WHERE ri.ADDRESS like "서울%"
GROUP BY rv.REST_ID
ORDER BY SCORE DESC, ri.FAVORITES DESC;
