SELECT DISTINCT(cc.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR as cc
         JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as ch
              ON cc.CAR_ID=ch.CAR_ID
WHERE cc.CAR_TYPE="세단" and MONTH(ch.START_DATE)=10
ORDER BY cc.CAR_ID DESC;