# 참고 :
# https://velog.io/@kwb020312/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EA%B3%BC%EC%9D%BC%EB%A1%9C-%EB%A7%8C%EB%93%A0-%EC%95%84%EC%9D%B4%EC%8A%A4%ED%81%AC%EB%A6%BC-%EA%B3%A0%EB%A5%B4%EA%B8%B0
# https://school.programmers.co.kr/questions/42827

# 1. FLAVOR 컬럼 값이 같다는 것을 이용해 WHERE 절에 명시해서 JOIN하는 방법
SELECT DISTINCT i.FLAVOR
  FROM ICECREAM_INFO i, FIRST_HALF f
  WHERE f.FLAVOR = i.FLAVOR AND f.TOTAL_ORDER > 3000 AND i.INGREDIENT_TYPE = 'fruit_based'
ORDER BY f.TOTAL_ORDER DESC;

# 2. 직접 JOIN문을 써서 JOIN하는 방법
# SELECT i.FLAVOR FROM ICECREAM_INFO as i
# LEFT JOIN FIRST_HALF as f
# ON i.FLAVOR = f.FLAVOR
# WHERE f.TOTAL_ORDER > 3000 AND i.INGREDIENT_TYPE LIKE 'fruit_based'
# ORDER BY f.TOTAL_ORDER DESC;